# Generated by Django 6.0.6 on 2026-07-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0002_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='recommended_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='doctors.specialization'),
        ),
    ]
