# Generated by Django 6.0.6 on 2026-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('general_chat', 'General Chat'), ('pre_visit', 'Pre Visit'), ('post_visit', 'Post Visit'), ('follow_up', 'Follow Up'), ('specialist_recommendation', 'Specialist Recommendation')], max_length=50),
        ),
    ]
