# Generated by Django 6.0.6 on 2026-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
