# Generated by Django 6.0.6 on 2026-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_reschedule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_sync_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
